Method별 결과 출력 기능을 구현한다.
morak-morak/performance-tracker pull request #16
Opened 2023-01-04 12:21 UTC by leo0842

close #2 

<img width="958" alt="image" src="https://user-images.githubusercontent.com/42317507/210553991-8fab637a-2630-4318-9e5b-fd6666cb6ef4.png">

- 2개의 인덴트로 구분된다.
- 테스트 method 별 쿼리와 api 를 로깅한다.

2023-01-05 03:33 UTC, cjlee38 requested changes
고생하셨습니다 👍 구조상 어색한 부분이 있어서 RC 드렸으니 한번 확인해주세요 :)

2023-01-05 03:33 UTC, cjlee38 commented on src/main/java/com/morak/performancetracker/description/Descriptor.java
> +    void describe(String methodName);
사용하는 곳이 없네용
\+ `void describe(Result result);` 도 지워도 될 것 같아요~

2023-01-05 03:33 UTC, cjlee38 commented on src/main/java/com/morak/performancetracker/context/ContextManager.java
> +    void afterClass(String testClassName);
전반적인 실행 흐름이 어색한 것 같아서 여기에 모아서 정리해볼게요~

제가 생각했을 때, `junit` 패키지에 있는 `setup extension`은 각 단계에서 "무엇"을 해야할지는 모르고, 자신이 알고 있는 정보를 `context manager`에게 넘겨주는 역할이고, `context manager`는 각 단계에서 `context type` 별로 수행해야 하는 작업을 해야 한다고 생각해요.

그런데 현재 구조를 보면 `set up extension`에서 accumulator에게 직접 무언가 행위를 지정하고 있어요. 이러면 `endpoint context` 에서 뭔가 변화가 생겼을때 `set up extension` 과의 호환성을 다시 체크해야 하고, `set up extension`에 변화가 필요해지면 다시 `method context` 에 문제가 없는지 호환성을 체크해야 하고.. 이런식으로 변경의 여파가 커질 것 같아요. 그리고 보통 이런 상황을 "결합도가 높다"라고 표현하죠.

둘 째로, scope에 대한 labeling은 beforeEach 단계에서 수행되지만, context에 대한 labeling은 afterClass 단계에서 수행되고 있어요. 이 둘을 통일시키는게 개념적으로 이해하기가 더 수월하지 않을까요 ?

그래서 이 구조를 개선한다면, 두 가지 방법이 있을 것 같아요. Junit의 테스트 흐름은 beforeAll -> beforeEach -> afterEach -> afterAll 이니,
1. before(each, all) 단계에서 labeling을 수행한다. 그리고 after(each, all) 단계에서 labeling된 context나 scope에, accumulator로 꺼낸 값들을 add 한다.
2. 각 after단계에서 accumulator에 값을 꺼내고, labeling 작업을 수행한다. 

그러면 아마 context manager 인터페이스 signature에 변화가 생길 것 같은데, 이 부분도 String으로 받을 수 있고, 혹은 클래스 이름 혹은 메소드이름에 해당하는 String과 각 depth를 나타내는 enum을 필드로 갖는 녀석을 `ContextName`, `ContextId`, `ContextSignature` ... 등의 이름으로 만들어볼 수도 있을 것 같아요.

2023-01-05 07:32 UTC, Seungpang approved these changes
차리가 꼼꼼하게 리뷰해서 궁금한 부분에만 코멘트 달았습니다.
나머지는 컨벤션에 따라 final 키워드만 지우면 될 것 같아요!
고생하셨습니다.

2023-01-05 07:32 UTC, Seungpang commented on src/main/java/com/morak/performancetracker/context/MethodContextManager.java
> +    private List<Scope> scopes = new ArrayList<>();
어디에는 final이 붙고 안붙고 이런 이유가 있을까요?

2023-01-05 07:32 UTC, Seungpang commented on src/main/java/com/morak/performancetracker/context/Context.java
> +    public Context(final String name, final List<Scope> scopes) {
컨벤션에 따라 final 키워드를 제거하면 좋을 것 같아요

2023-01-05 13:30 UTC, cjlee38 approved these changes
final만 정리하고 merge 해주시면 될 것 같습니당~

2023-01-06 02:46 UTC, leo0842 commented on src/main/java/com/morak/performancetracker/context/MethodContextManager.java
> +    private List<Scope> scopes = new ArrayList<>();
context list 는 타입이 변경이 되지 않지만, scope list 는 변경이 될 수밖에 없어서 final 을 뺐습니다!

2023-01-06 02:55 UTC, merged