RestTemplate 기반 PerformanceTracker를 추가한다.
morak-morak/performance-tracker pull request #18
Opened 2023-01-05 04:11 UTC by cjlee38

close #8
webclient는 별도 이슈로 해결합니다.

2023-01-05 09:35 UTC, Seungpang requested changes
테스트도 꼼꼼하게 짜주셨네요. 
약간 주석한 부분이나 System.out 부분만 지워주시면 바로 approve 하겠습니다.

2023-01-05 09:35 UTC, Seungpang commented on src/main/java/com/morak/performancetracker/context/Result.java
> +        System.out.println((long) elapsed);
이 부분은 개발중 확인용인가요?

2023-01-05 09:35 UTC, Seungpang commented on src/test/java/com/morak/performancetracker/aop/rest/RestMonitorAopTest.java
> +        System.out.println("aopProxy = " + aopProxy);
```suggestion
        assertThat(aopProxy).isTrue();
```
이걸로 바꿔도 될 것 같네요

2023-01-05 09:35 UTC, Seungpang commented on src/main/java/com/morak/performancetracker/aop/rest/RestMonitorAop.java
> +        ProxyFactoryBean proxyFactoryBean = new ProxyFactoryBean();
ProxyFactory와 ProxyFactoryBean의 차이가 궁금해서 찾아봤는데 ProxyFactoryBean은 Ioc 컨테이너와 함께 사용하고 ProxyFactory는 Ioc 컨테이너와 독립적으로 사용하네요

2023-01-05 09:35 UTC, Seungpang commented on src/main/java/com/morak/performancetracker/context/ResultMapper.java
> +        if (monitor instanceof RestMonitor) {
테스트 하는 monitor가 추가될때마다 instanceof를 추가하는게 좋을까요?
아니면 다형성을 활용해서 만드는게 좋을까요? 개인적인 궁금증입니다.

2023-01-05 09:35 UTC, Seungpang commented on src/test/java/com/morak/performancetracker/aop/rest/RestAdviceTest.java
> +//                () -> assertThat(monitor.getElapsedTime()).isNotZero(),
이 부분은 필요없는 부분인가요?

2023-01-05 11:13 UTC, cjlee38 commented on src/test/java/com/morak/performancetracker/aop/rest/RestAdviceTest.java
> +//                () -> assertThat(monitor.getElapsedTime()).isNotZero(),
꼼꼼히 확인하지 못했네용. 감사합니당

2023-01-05 11:14 UTC, cjlee38 commented on src/main/java/com/morak/performancetracker/context/ResultMapper.java
> +        if (monitor instanceof RestMonitor) {
이 부분은 아직 고민중입니당. monitor들이 갖는 속성들이 저마다 조금씩 달라서, 추상화를 적용할지말지, 적용한다면 어떻게 적용할지에 대해서 결정하지 못해서요. 당장은 팩토리패턴 느낌으로 ResultMapper한테 맡기는게 좋아보입니당. 어느정도 추가할만큼 하고나면 그 때 추상화를 들어가도 괜찮을 것 같아요.

2023-01-05 11:26 UTC, cjlee38 commented on src/main/java/com/morak/performancetracker/aop/rest/RestMonitorAop.java
> +        ProxyFactoryBean proxyFactoryBean = new ProxyFactoryBean();
그러게요. 아직 잘 이해는 안되지만

ProxyFactoryBean is essentially the same thing as ProxyFactory (they have the same superclass). It just additionally implements FactoryBean so Spring can control its lifecycle.

라고 하네용 [출처](https://stackoverflow.com/questions/47111867/what-is-the-difference-between-proxyfactory-and-proxyfactorybean-in-spring-frame)

2023-01-05 13:12 UTC, Seungpang approved these changes

2023-01-06 05:19 UTC, leo0842 approved these changes
상당히 깔끔하네요 ㅎㅎㅎ 수고하셨습니다!

2023-01-06 05:37 UTC, merged