JsonDescriptor를 추가한다.
morak-morak/performance-tracker pull request #21
Opened 2023-01-06 07:48 UTC by Seungpang

## 아직 미정인 부분
```json
[
  {
    "name": "findMember",
    "summaries": [
      {
        "name": "insert into member (id, name) values (default, ?)",
        "elapsed": 4.0818668E7,
        "result": "Result{name\u003d\u0027insert into member (id, name) values (default, ?)\u0027, elapsed\u003d4.0818668E7}"
      },
      {
        "name": "insert into member (id, name) values (default, ?)",
        "elapsed": 287433.0,
        "result": "Result{name\u003d\u0027insert into member (id, name) values (default, ?)\u0027, elapsed\u003d287433.0}"
      },
      {
        "name": "select member0_.id as id1_0_0_, member0_.name as name2_0_0_ from member member0_ where member0_.id\u003d?",
        "elapsed": 760254.0,
        "result": "Result{name\u003d\u0027select member0_.id as id1_0_0_, member0_.name as name2_0_0_ from member member0_ where member0_.id\u003d?\u0027, elapsed\u003d760254.0}"
      }
    ]
  },
  {
    "name": "saveMebers",
    "summaries": [
      {
        "name": "insert into member (id, name) values (default, ?)",
        "elapsed": 1471494.0,
        "result": "Result{name\u003d\u0027insert into member (id, name) values (default, ?)\u0027, elapsed\u003d1471494.0}"
      },
      {
        "name": "insert into member (id, name) values (default, ?)",
        "elapsed": 285177.0,
        "result": "Result{name\u003d\u0027insert into member (id, name) values (default, ?)\u0027, elapsed\u003d285177.0}"
      }
    ]
  },
  {
    "name": "findandDeleteMember",
    "summaries": [
      {
        "name": "insert into member (id, name) values (default, ?)",
        "elapsed": 314577.0,
        "result": "Result{name\u003d\u0027insert into member (id, name) values (default, ?)\u0027, elapsed\u003d314577.0}"
      },
      {
        "name": "insert into member (id, name) values (default, ?)",
        "elapsed": 257586.0,
        "result": "Result{name\u003d\u0027insert into member (id, name) values (default, ?)\u0027, elapsed\u003d257586.0}"
      }
    ]
  }
]
```
지금은 현재 하나의 class에서 실행한 테스트 결과를 누적해서 json에 쌓고 있습니다.
하나의 파일에 모든 테스트의 결과를 누적해서 저장하는게 좋을지 아니면 각 테스트 클래스별로 분리해야할지 고민이네요
그래서 일단은 한번 피드백을 받은 다음에 수정하겠습니다.

[개발일지](https://wheat-stoplight-3b3.notion.site/JsonDescriptor-5aa688f32b5449efa081566abab8fe86)
close #10

2023-01-06 08:22 UTC, cjlee38 requested changes
고생하셨습니다~ JsonDescriptor 출력 결과를 어떻게 찍을지 경우의 수를 생각해보면 아래와 같이 있을 것 같은데요.

1. 하나의 파일로 관리한다. 그 와중에 여러 번 테스트 했을 경우
    1.1. 기존 파일을 replace 한다.
    1.2. 기존 파일에 append 한다.
2. 여러 개의 파일로 관리한다. 그 와중에 여러 번 테스트 했을 경우
   2.1. 모두 별도의 파일로 구성한다.
   2.2. 날짜별로 구성한다. 같은날에 여러 번 테스트를 했다면
      2.2.1. 해당 파일에 append 한다.
      2.2.2. 해당 파일을 replace 한다.

1.2 방식이나, 2.2.1 방식을 이용하는 건 결국 logging descriptor와 다를바가 크게 없다고 생각이 들어서(그저 예쁘게 보여주기 위함인 목적이 될 것 같아요.) 제외하고,

2.2.2. 는 구현도 까다로울 것 같고, 저렇게 결과가 나오기를 기대하는 케이스가 거의 없을 것 같아요. 그러면 1.1 혹은 2.1. 인데, "과거의 performance와 현재의 performance를 비교한다" 라는 관점에서 봤을 때 2.1. 이 더 낫다고 생각이 드네요. 연월일시분초 까지만 해서 file 뒤에 덧붙여도 괜찮을 것 같아용.

```
class A {
    void test1();
    void test2();
}

class B {
    void test3();
    void test4();
}
```

1.1 2번 실행 -> `/logs/performance.json` 2번째 실행결과로 그냥 replace (기존파일 삭제 & 새로 생성)
2.1 2번 실행 -> `/logs/performance-2023-01-09-16:19:30.json` & `/logs/performance-2023-01-09-16:19:55.json`

\+ Result toString() 결과는 안찍어도 될것같습니당

2023-01-06 08:22 UTC, cjlee38 commented on src/main/java/com/morak/performancetracker/description/JsonDescriptor.java
> +}
EOF !

2023-01-06 08:22 UTC, cjlee38 commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +}
EOF !

2023-01-06 08:22 UTC, cjlee38 commented on src/main/java/com/morak/performancetracker/description/JsonDescriptor.java
> +    private ObjectMapper objectMapper;
생성자 주입받는건 어떤가요? `@Value`는 `@ConfigurationProperties` 를 이용해도 좋을 것 같네요.

[참고](https://mangkyu.tistory.com/189)

2023-01-06 08:22 UTC, cjlee38 commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +class DescriptorTest {
describe 결과가 예상한 문자열인지 테스트하는 것도 추가해보면 좋을것같네요

2023-01-09 14:56 UTC, Seungpang commented on src/main/java/com/morak/performancetracker/description/JsonDescriptor.java
> +    private ObjectMapper objectMapper;
`@ConfigurationProperties` 사용하는 방식으로 바꿨습니다. `@EnableConfigurationProperties`을  JsonDescriptor에 달아줬습니다. 그리고 어떤 class인지 명시를 해줘야 하더라구요
```java
@Component
@EnableConfigurationProperties(value = DescriptorProperties.class)
@ConditionalOnProperty(value = "com.morak.performance-tracker.format", havingValue = "json")
public class JsonDescriptor implements Descriptor {
```

2023-01-09 14:57 UTC, Seungpang commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +class DescriptorTest {
log쪽은 ListAppender<ILoggingEvent> logWatcher을 활용하여 테스트를 추가했습니다. 다만 json은 테스트를 어찌 할지 고민이네용

2023-01-09 15:02 UTC, Seungpang reviewed
현재 EndpointContextManager와 MethodContextManager의 afterAll에서 서로descriptor.describe하는 부분에서 방식에 차이가 존재해서 이걸 JsonDescriptor에서 구현으로 해결하려고 했습니다.

하지만 하다가 너무 복잡성만 올라가는 것 같아서 일단 List<Context>를 가지는 Root클래스로 describe 하는 부분을 통일 시켰습니다. 따라서 afterAll부분에서 describe는 한번만 호출하도록 변경되었습니다.

현재 충돌나는 부분은 맨 마지막에 고치겠습니다 :)

2023-01-10 05:09 UTC, cjlee38 requested changes
고생하셨습니당 ~ 몇 가지만 코멘트 달았으니 참고해주세여

2023-01-10 05:09 UTC, cjlee38 commented on src/main/java/com/morak/performancetracker/description/JsonDescriptor.java
> +@EnableConfigurationProperties(value = DescriptorProperties.class)
이 어노테이션은 `PerformanceConfiguration` 쪽으로 옮겨가는게 어떨까요 ?

2023-01-10 05:09 UTC, cjlee38 commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +        private ListAppender<ILoggingEvent> logWatcher;
👍

2023-01-10 05:09 UTC, cjlee38 commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +                    () -> assertThat(loggingEvents.get(2).getMessage()).isEqualTo("        Result{name='firstQuery', elapsed=2.0}")
```
() -> assertThat(loggingEvents.get(0).getMessage()).contains("firstClass"),
() -> assertThat(loggingEvents.get(1).getMessage()).contains("firstMethod"),
() -> assertThat(loggingEvents.get(2).getMessage()).contains("firstQuery")
```

2023-01-10 05:09 UTC, cjlee38 commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +        }
이 코드는 뭘까용 ?

2023-01-10 09:03 UTC, Seungpang commented on src/main/java/com/morak/performancetracker/description/JsonDescriptor.java
> +@EnableConfigurationProperties(value = DescriptorProperties.class)
PerformanceConfiguration로 변경했습니당

2023-01-10 09:04 UTC, Seungpang commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +                    () -> assertThat(loggingEvents.get(2).getMessage()).isEqualTo("        Result{name='firstQuery', elapsed=2.0}")
출력하는 형식이 변경된다고 했을때 위의 형식이면 바꾸지 않아도도겠네요

2023-01-10 09:05 UTC, Seungpang commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +        }
미처 지우지 못했네요!

2023-01-10 11:29 UTC, cjlee38 approved these changes
고생하셧습니당~ conflict만 해결하고 merge 부탁드립니당

2023-01-13 07:19 UTC, leo0842 approved these changes
수고 많으셨습니다!! 고민하고 고생한 흔적이 코드에 묻어나네요 ㅎㅎ

2023-01-13 07:19 UTC, leo0842 commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +            descriptor = context.getBean(Descriptor.class);
descriptor 에 주입을 `getBean` 을 통해 얻는 이유는 명시적으로 보이기 위함일까요?? `@Autowired` 를 통해서도 주입받을 수 있을 것 같아서요!

2023-01-13 07:19 UTC, leo0842 commented on src/main/java/com/morak/performancetracker/description/LoggingDescriptor.java
> +    }
기존 방식을 크게 바꾸지 않고 적용한 모습 너무 좋네요 👍

2023-01-13 07:32 UTC, Seungpang commented on src/test/java/com/morak/performancetracker/description/DescriptorTest.java
> +            descriptor = context.getBean(Descriptor.class);
명시적으로 보이기 위함인데 어차피 SpringBootTest를 하는 입장에서 `@Autowired`를 통해 주입받는 방식이 더 깔끔할 것 같네요!

2023-01-13 07:35 UTC, merged