docs: README.md 의 내용을 추가하고, 한글 문서를 작성한다.
morak-morak/performance-tracker pull request #22
Opened 2023-01-09 11:46 UTC by cjlee38

close #11 

description 쪽은 json descriptor 가 merge 되면 진행하겠습니당.

우선 간단하게 피드백 부탁드려용

2023-01-11 06:20 UTC, Seungpang requested changes
고생하셨습니다! 의미없는 `-` 부분 지워주세요 :)
그리고 README는 영문, 한글 버전인데 Contexts, Descriptions 등등 영문밖에 없네요 ㅠ

2023-01-11 06:20 UTC, Seungpang commented on README.md
> +If you wanna know further examples, see [this](./docs/EXAMPLE.md)
EXAMPLE.md는 추후에 추가하는 거겠죠?

2023-01-11 06:20 UTC, Seungpang commented on README_KR.md
> +-
해당 부분 필요없어 보여요!

2023-01-11 06:36 UTC, cjlee38 commented on README.md
> +If you wanna know further examples, see [this](./docs/EXAMPLE.md)
현 `Monitors.md` 가 원래 example 이었어서 ㅋㅋ; 깜빡하고 수정을 못했네요. 반영했습니당

2023-01-11 06:36 UTC, cjlee38 commented on README_KR.md
> +-
👍

2023-01-11 06:37 UTC, cjlee38 commented
피드백 반영했습니당. 혹시 내용적인 측면에서 문장이 어색하거나, 영어가 이상하거나 하는 등의 문제가 보이면 말씀해주세용

2023-01-13 07:15 UTC, Seungpang approved these changes
JsonDescriptor에 대한 예시만 추가하면 끝이겠네요 고생하셨습니다. 일단 approve하겠습니다.

2023-01-17 07:06 UTC, leo0842 approved these changes
수고하셨습니다! 조금 더 완성이 되면 다시 보죠

2023-01-17 07:06 UTC, leo0842 commented on README_KR.md
> +  file: {FILE_NAME_TO_WRITE_RESULT} # default is 'performance'
format 추가 부탁!

2023-01-17 07:06 UTC, leo0842 commented on README.md
>  Track your application's performance based on Spring.
여기를 조금 더 상세하게 하는 건 어떤가요??

2023-03-12 06:46 UTC, merged