refactor: Result를 composite pattern으로 전환한다.
morak-morak/performance-tracker pull request #32
Opened 2023-07-03 07:05 UTC by leo0842

close #15

composite pattern 으로 전환하였습니다.

2023-07-03 08:50 UTC, cjlee38 requested changes
일단 웹으로 간단하게 살펴봤습니당. 리뷰반영하시면 checkout 해서 한번 살펴볼게용

2023-07-03 08:50 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/ResultComposite.kt
> +        subResults.forEach(Consumer { subResult: Result ->
consumer 빼고 it 로 바꿔주세용

2023-07-03 08:50 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/TestMetadata.kt
> +            }
여기 for 문 대신에 다른걸로 바꿀수 있을 것 같은데요.
`reduce` 나 `fold` 를 사용하면 될 것 같아요.

\+ ROOT 랑 of 사이에 줄바꿈 넣어주세요

2023-07-03 08:50 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/junit/PerformanceTrackerSetupExtension.kt
> +            .forEach { manager: ContextManager ->
it 으로 바꿔주세요

2023-07-03 08:50 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/junit/PerformanceTrackerSetupExtension.kt
> +            .forEach(Consumer { manager: ContextManager ->
여기두 Consumer 빼고 it 으로 바꿔주세요

2023-07-03 08:50 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/MethodContextManager.kt
> +        for (dto in flatResults(accumulator.results)) {
forEach 로 바까주세용

2023-07-03 08:50 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/ResultComposite.kt
> +    private val _subResults: MutableList<Result>
여기 default parameter 로 mutableListOf 를 넣어둘까요 ?

2023-07-03 08:50 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/EndpointContextManager.kt
> +//            .toMutableList()
주석 지워주세용

2023-07-03 08:50 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/EndpointContextManager.kt
> +        return summary.map() { (key, value) ->
소괄호 없애주세용

\+ 아니면 toResult 를 summarize 안에 inline 시켜주세요

2023-07-03 08:50 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/EndpointContextManager.kt
> +            .toMutableList()
List를 mutable하게 다룰 필요가 없다면 List 로 바꿔주세요.

코틀린에서는 최대한 immutable 로 다루는게 좋습니당.

2023-07-03 10:18 UTC, leo0842 commented on src/main/kotlin/com/morak/performancetracker/context/ResultComposite.kt
> +        subResults.forEach(Consumer { subResult: Result ->
넵~! 아래의 유사한 리뷰 모두 반영하였습니다!

2023-07-03 10:18 UTC, leo0842 commented on src/main/kotlin/com/morak/performancetracker/context/TestMetadata.kt
> +            }
forEach 도 고민했었는데 reduce 가 더 어울릴 것 같아서 reduce 로 수정하였습니다!

2023-07-03 10:20 UTC, leo0842 commented on src/main/kotlin/com/morak/performancetracker/context/EndpointContextManager.kt
> +        return summary.map() { (key, value) ->
summarize 메서드 내부에 인라인 하는게 읽기도 편하고 깔끔해보여서 인라인으로 수정하였습니다!

2023-07-03 10:22 UTC, leo0842 commented on src/main/kotlin/com/morak/performancetracker/context/EndpointContextManager.kt
> +            .toMutableList()
이 부분에서는 반환값이 ResultComposite 의 프로퍼티로 들어가는데, 해당 클래스에서 add 해주는 로직이 있어서 mutable 로 하였습니다.

2023-07-03 11:32 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/EndpointContextManager.kt
> +            .toMutableList()
생성자에서 immutable 로 받고, 내부에서 mutable 하게 다룰 수 있습니당.

<img width="582" alt="image" src="https://github.com/morak-morak/performance-tracker/assets/52564093/fea07bdd-fe2b-4cdb-b64e-16be9fb597e5">

2023-07-03 11:42 UTC, cjlee38 requested changes
👍 조금만 더 다듬어봅시당

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/EndpointContextManager.kt
> +            .map { pair -> ResultLeaf(pair.first, pair.second) }
한줄로 처리할 수도 있을 것 같네용

```kotlin
.map { (key, value) -> ResultLeaf(key, value.average { it.elapsed }) }
```

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/Accumulator.kt
> +    private var _results: MutableMap<String, MutableList<MonitorResult>> = mutableMapOf()
val 로 다뤄도 될 것 같아요

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/MethodContextManager.kt
> +    private val root: ResultComposite = ResultComposite(TestMetadata.ROOT, mutableListOf());
default parameter 를 추가했으니 `mutableListOf` 를 넘겨줄 필요는 없어지겠네용

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/ResultComposite.kt
> +import java.util.function.Consumer
import 제거해주세염

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/MethodContextManager.kt
> +        flatResults(accumulator.results).forEach { it: MonitorResult ->
MonitorResult type 을 지정하지 않으면 `it: MonitorResult ->` 이 부분을 제거할 수 있겠네요

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/ResultComposite.kt
> +    private val _subResults: MutableList<Result> = mutableListOf()
여기도 `ResultLeaf` 와 마찬가지로, 생성자로 list 를 받고 내부적으로 mutable  로 관리해주세용

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/ResultComposite.kt
> +        subResults.forEach { it: Result ->
여기도 `it: Result` 를 없애주세용

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/TestMetadata.kt
> +    }
여기 fun 대신 val 로 처리하는게 어떨까요 ?

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/context/TestMetadata.kt
> +            val name = ROOT_NAME.plus(NAME_DELIMITER).plus(names.reduce { a, b -> a.plus(NAME_DELIMITER).plus(b) })
`plus` 는 `+` 기호로 바꿔주세용.
람다 파라미터도 a, b  대신 `acc, cur` 와 같은 이름이 낫지 않을까용 ?

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/description/LoggingDescriptor.kt
> +        entry.subResults.forEach { subResult -> describeInternal(subResult, indent + 1) }
여기도 it 로 바꿔주세요

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/junit/PerformanceTrackerSetupExtension.kt
> +            .forEach { it: ContextManager ->
여기도 `it: ContextManager ->` 를 제거해주세용

2023-07-03 11:42 UTC, cjlee38 commented on src/test/kotlin/com/morak/performancetracker/description/DescriptorTest.kt
> +                mutableListOf(
여기도 listOf 로 바꿀 수 있겠네요

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/junit/PerformanceTrackerSetupExtension.kt
> +            .forEach { it: ContextManager ->
여기두용

2023-07-03 11:42 UTC, cjlee38 commented on src/main/kotlin/com/morak/performancetracker/junit/PerformanceTrackerSetupExtension.kt
>  import java.util.function.Consumer
import 제거해주세용

2023-07-03 14:18 UTC, leo0842 commented on src/main/kotlin/com/morak/performancetracker/context/EndpointContextManager.kt
> +            .toMutableList()
와 이렇게도 되네요. 이 클래스와 더불어 Composite 에도 같은 방식으로 수정하였습니다~!

2023-07-03 14:19 UTC, leo0842 commented on src/main/kotlin/com/morak/performancetracker/context/EndpointContextManager.kt
> +            .map { pair -> ResultLeaf(pair.first, pair.second) }
하 이 방법을 찾다가 실패했는데 이렇게 하면 되네용! 바로 수정하였습니다.

2023-07-03 14:19 UTC, leo0842 commented on src/main/kotlin/com/morak/performancetracker/context/ResultComposite.kt
> +import java.util.function.Consumer
🥲

2023-07-03 14:20 UTC, leo0842 commented on src/main/kotlin/com/morak/performancetracker/context/MethodContextManager.kt
> +    private val root: ResultComposite = ResultComposite(TestMetadata.ROOT, mutableListOf());
불변이 이거네요

2023-07-03 14:21 UTC, leo0842 commented on src/main/kotlin/com/morak/performancetracker/context/TestMetadata.kt
> +    }
넵 굳이 function 으로 있을 필요가 없는 것 같습니다! val 로 수정하였습니다~!

2023-07-04 12:03 UTC, cjlee38 approved these changes
👍 수고하셨습니다 ~

마지막에 줄바꿈정도 가볍게 바꾸었으니 한번 보시고 merge 처리 해주시면 될 것 같습니다

2023-08-26 12:01 UTC, merged